name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Build Mac
      run: cargo build --verbose
