name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: macos-latest-xlarge

    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install Linux target
      run: rustup target add x86_64-unknown-linux-gnu
    - name: Install Win target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build Mac
      run: cargo build --verbose
    - name: Build Linux
      run: cargo build --verbose --target x86_64-unknown-linux-gnu
    - name: Build Win
      run: cargo build --verbose --target x86_64-pc-windows-gnu
