name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install rustup
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
    - name: Install cross
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Install Mac target
      run: rustup target add aarch64-apple-darwin
    - name: Install Win target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build Linux
      run: cargo build --verbose
    - name: Build Mac
      run: cross build --verbose --target aarch64-apple-darwin
    - name: Build Win
      run: cross build --verbose --target x86_64-pc-windows-gnu
